todo
Shohzod1505/Android_22-23 pull request #10
Opened 2023-01-07 20:11 UTC by Shohzod1505

-- Весь основной функционал готов.
-- Завтра добавлю свою тему и переключение между ней
-- Почему-то список не обновляется хотя сделано все через DiffUtils и ListAdapter, в точно такой же домашке все работало, возможно все из-за бд, так как на летней практике, чтобы список обновлялся я с LiveData работал. 

https://user-images.githubusercontent.com/92218360/211168703-cf67fda6-aab7-439c-a63f-289148045458.mp4

2023-01-08 11:02 UTC, Shohzod1505 commented
-- Все таки добавил LiveData для корректного обновления списка

2023-01-08 23:28 UTC, NailShaykhrazievItis requested changes

2023-01-08 23:28 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/itis/kpfu/homework/data/dao/TodoListDao.kt
> +    suspend fun findById(id: Int): TodoList
А если не найдется? Добавь нуллабилити, чтобы было : TodoList?

2023-01-08 23:28 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/itis/kpfu/homework/data/dao/TodoListDao.kt
> +    fun getAll(): LiveData<List<TodoList>>
Не надо livedata, почти мертвая технология, если хочешь именно подписаться лучше флоу использовать

2023-01-08 23:28 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/itis/kpfu/homework/screen/ListFragment.kt
> +                true
а смена темы(((

2023-01-08 23:28 UTC, NailShaykhrazievItis commented on app/src/main/java/ru/itis/kpfu/homework/screen/EditListFragment.kt
> +                            parentFragmentManager.beginTransaction()
Можно было вынести в отдельный метод
` parentFragmentManager.beginTransaction()
                                .replace(R.id.fragment_container, fragment)
                                .addToBackStack(tag)
                                .commit()`

2023-01-09 17:12 UTC, Shohzod1505 commented
Все ваши комменты разобрал, смену темы добавил со светлой на темную, но прям свою тему не стал делать (цвета подбирать), так как дизайнер хреновый))

2023-02-16 14:30 UTC, closed without merging